import { describe, expect, it } from 'vitest'
import { LevelVault, type LevelSolver } from '../lib/levels'
import { generateLevel } from '../../src/board/generator/index'
import { DIFFICULTY_BANDS, matchSchedule } from '../../src/multiplayer/match'

/** A solver that records how often it ran, so caching can be observed. */
const counting = (): { solve: LevelSolver; calls: number[] } => {
  const calls: number[] = []
  return {
    calls,
    solve: (levelNumber) => {
      calls.push(levelNumber)
      return [levelNumber % 5, (levelNumber + 1) % 5]
    },
  }
}

describe('caching', () => {
  it('generates a level once however many times it is asked for', () => {
    const { solve, calls } = counting()
    const vault = new LevelVault(solve)
    for (let i = 0; i < 20; i++) vault.solutionFor(7)
    expect(calls).toEqual([7])
    expect(vault.generated).toBe(1)
  })

  it('pre-warms without the caller having to know whether it already has one', () => {
    const { solve, calls } = counting()
    const vault = new LevelVault(solve)
    vault.warm(3)
    vault.warm(3)
    vault.warm(null)
    vault.warm(undefined)
    expect(calls).toEqual([3])
    expect(vault.has(3)).toBe(true)
  })

  it('seeds from a snapshot so an evicted room does not rebuild what it played', () => {
    const { solve, calls } = counting()
    const vault = new LevelVault(solve, { '11': [0, 2, 4, 1, 3] })
    expect(vault.solutionFor(11)).toEqual([0, 2, 4, 1, 3])
    expect(calls).toEqual([])
    expect(vault.generated).toBe(0)
  })

  it('round-trips its snapshot', () => {
    const { solve } = counting()
    const vault = new LevelVault(solve)
    vault.warm(4)
    vault.warm(9)
    const restored = new LevelVault(solve, vault.snapshot())
    expect(restored.has(4)).toBe(true)
    expect(restored.has(9)).toBe(true)
  })

  it('ignores junk in a stored snapshot rather than throwing on wake', () => {
    const { solve, calls } = counting()
    const vault = new LevelVault(solve, { notANumber: [1], '5': [0, 1] } as never)
    expect(vault.has(5)).toBe(true)
    expect(calls).toEqual([])
  })
})

describe('verification against a real level', () => {
  const levelNumber = DIFFICULTY_BANDS.easy.from
  const level = generateLevel(levelNumber)

  it('accepts the levels own solution', () => {
    const vault = new LevelVault()
    expect(vault.verify(levelNumber, level.solution)).toBe(true)
  })

  it('refuses a solution with one cat moved', () => {
    const vault = new LevelVault()
    const tampered = [...level.solution]
    tampered[0] = (level.solution[0]! + 1) % level.size
    expect(vault.verify(levelNumber, tampered)).toBe(false)
  })

  it('refuses a claim of the wrong length', () => {
    const vault = new LevelVault()
    expect(vault.verify(levelNumber, level.solution.slice(1))).toBe(false)
    expect(vault.verify(levelNumber, [...level.solution, 0])).toBe(false)
  })

  it('refuses another level solution', () => {
    const vault = new LevelVault()
    const other = generateLevel(levelNumber + 1)
    if (other.size !== level.size) return
    expect(vault.verify(levelNumber, other.solution)).toBe(false)
  })

  it('verifies the whole of a scheduled match', () => {
    // The shape of what the room actually does: a schedule of level numbers,
    // each one generated by the server and compared against a client claim.
    const schedule = matchSchedule('server-levels-test', 'easy', 5)
    const vault = new LevelVault()
    for (const spec of schedule) {
      const solved = generateLevel(spec.levelNumber)
      expect(solved.size).toBe(spec.size)
      expect(vault.verify(spec.levelNumber, solved.solution)).toBe(true)
    }
    expect(vault.generated).toBe(schedule.length)
  })
})
