/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayLevelNumberRouteImport } from './routes/play.$levelNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelNumberRoute = PlayLevelNumberRouteImport.update({
  id: '/play/$levelNumber',
  path: '/play/$levelNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/settings': typeof SettingsRoute
  '/play/$levelNumber': typeof PlayLevelNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/settings': typeof SettingsRoute
  '/play/$levelNumber': typeof PlayLevelNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/settings': typeof SettingsRoute
  '/play/$levelNumber': typeof PlayLevelNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/levels' | '/multiplayer' | '/settings' | '/play/$levelNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels' | '/multiplayer' | '/settings' | '/play/$levelNumber'
  id:
    | '__root__'
    | '/'
    | '/levels'
    | '/multiplayer'
    | '/settings'
    | '/play/$levelNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsRoute: typeof LevelsRoute
  MultiplayerRoute: typeof MultiplayerRoute
  SettingsRoute: typeof SettingsRoute
  PlayLevelNumberRoute: typeof PlayLevelNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelNumber': {
      id: '/play/$levelNumber'
      path: '/play/$levelNumber'
      fullPath: '/play/$levelNumber'
      preLoaderRoute: typeof PlayLevelNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsRoute: LevelsRoute,
  MultiplayerRoute: MultiplayerRoute,
  SettingsRoute: SettingsRoute,
  PlayLevelNumberRoute: PlayLevelNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
